spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sustcII  # change this to your own jdbc url
    username: postgres  # change this to your own username (avoid using a superuser)
    password: 747576  # change this to your own password

    hikari:
      connection-timeout: 180000
      leak-detection-threshold: 120000

logging:
  level:
    root: off
    io.sustc: debug
  file:
    name: logs/${LOG_FILE_NAME:test}.log
  

---

benchmark:
  data-path: data
  student-mode: true

spring:
  datasource:
    hikari:
      maximum-pool-size: 30